apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-deployment
  template:
    metadata:
      labels:
        app: server-deployment
    spec:
      containers:
        - name: server-deployment
          image: threshbesthook/serverside:1
          ports:
            - containerPort: 5000
